spring:
  application:
    name: OrdinaMii

  config:
    import: optional:classpath:passwords.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/OrdinaMii

  datasource:
    url: jdbc:postgresql://localhost:5433/OrdinaMii
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  app:
    uploads:
      dishes-directory: uploads/dishes
server:
  port: 8080

logging:
  file:
    name: logs/ordinamii.log

  level:
    root: info
    com.example.ordinaMii: debug
    org.springframework.security: info
    org.hibernate.SQL: warn

  logback:
    rollingpolicy:
      file-name-pattern: logs/ordinamii-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB