spring:
  application:
    name: OrdinaMii
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/OrdinaMii

  datasource:
    url: jdbc:postgresql://localhost:5433/OrdinaMii
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080